### ISSUE TITLE
Update of test workflow to use latest node

### ISSUE THREAD

**Issue by derberg** [asyncapi/ts-nats-template#543]
#### Reason/Context

[This](https://github.com/asyncapi/ts-nats-template/blob/master/.github/workflows/pull-request-example-testing.yml#LL18C27-L18C27) workflow uses node action `v1` and node `13`

Because of https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/ it should be updated to use node 14 at least, but probably best is 18

12 is deprecated soon and 13 is not even LTS release

#### Description

replace 
```yml
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13
```

with
```yml
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
```

also change `actions/checkout@v2` to `actions/checkout@v3` as `v2` runs on node12

@jonaslagoni please confirm node version and you can probably mark it as good first issue using `ci-cd` keyword
