### ISSUE TITLE
Template does not follow the specification

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/ts-nats-template#87]
#### Describe the bug
When defining operations in your AsyncAPI document you define it from the perspective of the users of the API and not what the actual application should do. 

The only way currently the template generates the source code is by generating it for the application itself and not for the user which is the opposite of what the specification defines and can be confusing.

#### How to Reproduce
Generally when specifying an AsyncAPI document for the application `game server` such as:
```yaml
  game/server/pickup:
    description: Channel used when a player picks up an item in-game
    subscribe: 
      message:
        payload:
          type: object
          $id: PlayerItemPickupPayload
          additionalProperties: false
          properties:
            pickupTimestamp:     
              type: string
              format: date-time
              description: The timestamp the item was picked up
```
This defines that others may subscribe (external) to this channel that the `game server` publishes (internal) to. 

Such a channel will currently generate a client wrapper for the `game server` rather than for the user meaning it will generate the signature
```js
public publishToGameServerPickup(
    message: PlayerItemPickupPayload
  ): Promise < void > {
    const nc: Client = this.jsonClient!;
    if (nc) {
      return gameServer.publish(
        message,
        nc
      );
    } else {
      return Promise.reject(NatsTypescriptTemplateError.errorForCode(ErrorCode.NOT_CONNECTED));
    }
  }
```

#### Expected behavior

[java-spring-template](https://github.com/asyncapi/java-spring-template/blob/aa74b48176ed4fae15cae31cfbe7c441c63a22b2/package.json#L79) - uses `inverseOperations` as a boolean.
[java-spring-cloud](https://github.com/asyncapi/java-spring-cloud-stream-template/blob/bfbb108f51b366ca7f7ed9f2df389cde40e380a0/package.json#L127)  - uses `view` with the properties `client` or `provider`.

I would suggest that we add a `for` or `view` keyword which by default generates for the user `external` and where one can specify it for the application itself `internal`. What would you recommend?
